<?php

use Drupal\Core\Routing\RouteMatchInterface;
/**
 * Implements hook_help().
 */
function musicsearch_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.musicsearch':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module will help you to search for music') . '</p>';
      $output .= '<p>' . t('') . '</p>';
      return $output;
    default:
  }
}
